import type { Metadata } from "next";
import "@/styles/globals.css";
import "@/styles/animations.css";
import { Geist } from "next/font/google";
import { SessionProvider } from "@/providers/SessionProvider";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Locale, routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { FontProvider } from "@/providers/FontProvider";
import { ThemeProvider } from "next-themes";
import { ColorProvider } from "@/providers/ColorProvider";
import Navbar from "@/components/shared/Navbar";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Next Test App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as Locale)) notFound();

  const messages = await getMessages();

  return (
    <html lang={locale} className={geist.variable} suppressHydrationWarning={false} suppressContentEditableWarning={false}>
      <body>
        <SessionProvider>
          <NextIntlClientProvider messages={messages}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              storageKey="app-theme"
            >
              <ColorProvider>
                <FontProvider>
                  <main className="w-full max-w-2xl min-h-dvh mx-auto px-4">
                    <Navbar />
                    {children}
                  </main>
                </FontProvider>
              </ColorProvider>
            </ThemeProvider>
          </NextIntlClientProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
